# Generated by Django 3.0.2 on 2020-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodie', '0002_hood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=700)),
                ('posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
