# Generated by Django 3.0.2 on 2020-01-17 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodie', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Required. Inform a valid email address.', max_length=200)),
                ('hood_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodie.Hood')),
            ],
        ),
    ]
