# Generated by Django 3.0.2 on 2020-01-18 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodie', '0007_auto_20200117_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hoody',
        ),
        migrations.AddField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hood_posts', to='hoodie.Hood'),
        ),
    ]
