# Generated by Django 3.0.2 on 2020-01-18 03:47

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodie', '0008_auto_20200118_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='hood_id',
            new_name='hoodie',
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='hood_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
        migrations.AddField(
            model_name='hood',
            name='hospital_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hood',
            name='police_line',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodie.Hood'),
        ),
    ]
