# Generated by Django 3.0.2 on 2020-01-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodie', '0009_auto_20200118_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
